### ISSUE TITLE
OMEMO test and appearance in the list

### ISSUE THREAD

**Issue by imolein** [iNPUTmice/ComplianceTester#112]
Hi,

since the ComplianceTester check OMEMO with publish-options (which I think is related to [this Gist](https://gist.github.com/iNPUTmice/7c52785ed69787516abb60e31703dbd2)), all servers, except conversations.im, appear with a red or grey field in the column "OMEMO encryption". I think this is extremely misleading, because User, which choose there server over this list will think, that all servers, except conversations.im, don't support OMEMO encryption. A lot of the servers running prosody, which currently don't support public-options in it's PEP module. That's why I suggest to add a well visible explanation, which will explain, that all servers support OMEMO encryption, but not public-options and that it isn't a safety risk, like it is explained in the Gist:

> Since there is no security risk involved in not changing the access model to open OMEMO clients should work with servers that support publish-options and with servers that do not.

Thanks and best regards,
Sebastian

**Comment by mightyBroccoli** [comment]
+1

**Comment by iNPUTmice** [comment]
While not a security problems the lack of publish-options is a huge usability problem as this limits OMEMO to contacts you have mutual presence subscription with.
Conversations users will except OMEMO to work with everyone. That's why Conversations requires publish-options.

**Comment by imolein** [comment]
> While not a security problems the lack of publish-options is a huge usability problem as this limits OMEMO to contacts you have mutual presence subscription with.
Why don't write this as explanation in your list and make the fields orange for example? But with no explanation at all and red or grey field it just say "This servers don't support OMEMO!", which is just wrong.

**Comment by owhen** [comment]
My server does not pass the OMEMO test in the ComplianceTester, but Conversations users are still able to communicate with my server using OMEMO. A appropriate explanation in the ComplianceTester list is really neccessary at this point.

**Comment by MotoGP-Fan** [comment]
I also disagree with this approach. An explanation of the Compliancetester result regarding to "XEP-0384: OMEMO Encryption" is **indispensable**.

**Comment by mightyBroccoli** [comment]
At least some sort of explanation to where the functionality is lacking without the omemo support would be a nice. This is confusing as hell for any new user looking for a an omemo compliant server. As our servers are complient just not to the omemo with strangers part.

**Comment by 1resu** [comment]
@iNPUTmice: I assume that your [xmpp service](https://account.conversations.im/) uses ejabberd. What are your settings to make publish-options work with ejabberd? I tried a lot of things but the compliance test still fails for OMEMO. Thanks in advance.

**Comment by iNPUTmice** [comment]
@1resu we had to manually patch our ejabberd to support this. I suggest you create a feature request at the ejabberd bug tracker.
Same goes for the prosody users in this thread by the way.

FWIW: [I received some very positive feedback for making publish-options (among other things) a requirement for PEP.](https://mail.jabber.org/pipermail/standards/2017-July/033059.html)

**Comment by imolein** [comment]
I think you misunderstood me/us. We appreciate your effort to make it a requirement. 

This ticket is about the fact that your Compliance list said our servers don't support OMEMO. It's more a request to make a short explanation in your list, that the servers still support OMEMO, but without one new feature.

**Comment by hansWURSCHT10000** [comment]
@iNPUTmice Could you share your patch or provide it upstream?

**Comment by trillerpfeife** [comment]
hey, just for your information regarding xep 163 (OMEMO without mutual presence) and ejabberd. in order to make this optional feature working there is a patch out there from holger. he posted the link for the patch a few month ago in the eng. conversations muc

https://jabber.fu-berlin.de/share/holger/FE0q8be5wG9spmZ2/publish-options.patch

its only working for 16.09 if you build from sourve
