### ISSUE TITLE
Better support for Java 9?

### ISSUE THREAD

**Issue by annando** [iNPUTmice/ComplianceTester#143]
When running ```java -jar ComplianceTester-0.2.2.jar``` the script returns ```Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException```.

The workaround is to call ```java --add-modules=java.xml.bind,java.activation -jar ComplianceTester-0.2.2.jar```. I found the solution here: https://github.com/aws/aws-sdk-java/issues/1092#issuecomment-335582842

It would be great if this could be fixed or at least that the workaround could be documented.

**Comment by iNPUTmice** [comment]
Isn’t this how Java 9 is supposed to work? I don’t think this is a 'workaround'

**Comment by annando** [comment]
I don't know. I don't work with Java at all and had to install the JDK just to work with the test suite. At least it should be documented, I think.

**Comment by iNPUTmice** [comment]
Closing this since this can be merged with #85
