### ISSUE TITLE
Support SSL/TLS only servers

### ISSUE THREAD

**Issue by Tragen** [iNPUTmice/ComplianceTester#165]
I cannot test my server as I don't get an encrypted connection.
The server forces TLS. Can you fix this please?

**Comment by Sanookmakmak** [comment]
Same me.

Result is:

`PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

Or:

`Transport Layer Security has been configured, but hasn't been negotiated.`

**Comment by Tragen** [comment]
After many tests and checking the source code I found the "problem".

This doesn't work
`ComplianceTester-0.2.3.jar compliance.tester@example.org mypwd`
It works only if your user doesn't have a . in the username

This works even with dots in the username.
`ComplianceTester-0.2.3.jar "compliance.tester@example.org" "mypwd"`
