### ISSUE TITLE
False positive with OMEMO

### ISSUE THREAD

**Issue by laolux** [iNPUTmice/ComplianceTester#187]
Hi, I tried your awesome xmpp compliance checker to test whether I set up my server correctly.
It shows that my server (ejabberd) passes most tests, including the XEP-0384 OMEMO test.
However, OMEMO support seems to be shaky at best. Only gajim managed to retrieve a key from miranda-ng, but not vice versa. Other clients such as pidgin (with lurch plugin) and chatsecure fail completely.
Is it possible to extend your compliance checker to test the key exchange for OMEMO?
Thanks a lot

**Comment by licaon-kter** [comment]
Does Conversations to Conversations work?

**Comment by laolux** [comment]
I can't test conversations, as I do not have an android device. Currently setting up a virtual machine to test gajim to gajim.

**Comment by laolux** [comment]
yes, thanks, I have those lines commented out already. I suspect my mistake to be elsewhere and tried to find it using the compliance tester, but it only shows problems with rooster versioning and XEP-0368: SRV records for XMPP over TLS.

**Comment by licaon-kter** [comment]
Try Dino to Dino too.

**Comment by laolux** [comment]
Never heard of Dino before, but will try it tomorrow and report back. Thanks for pointing it out.

**Comment by laolux** [comment]
Ok, so I tried Dino and set up 2 accounts on the same machine. OMEMO between those 2 accounts worked after restarting my server (nothing changed on the server). Pidgin on a different machine eventually got the OMEMO key from Dino, but not vice versa. So I suppose it's either a bug in miranda-ng, gajim and pidgin (lurch plugin), or my server is set up wrong (most likely).

In any case, OMEMO does work somewhat, so the results of the Compliance Tester are correct. Nonetheless, OMEMO is pretty unreliable on my server, but I suppose that is hard to check with this compliance test.

**Comment by licaon-kter** [comment]
Right now if Conversations and Dino work then OMEMO is ok. Gajim should too. Other might not (not enough development on their side)

**Comment by laolux** [comment]
Ok, so some more testing reveals that Dino always correctly sends it's key (sometimes restarts of one or the other client are required). However, other clients are very picky about sending their key. As others have reported success with their servers and clients I still suspect an error with my setup. 
However, that is unrelated to this compliance test. Therefore this issue should be closed and kept only for reference in case others encounter the same problem.
