### ISSUE TITLE
XEP-0313: Message Archive Management (MUC) checking is not right

### ISSUE THREAD

**Issue by luweitest** [iNPUTmice/ComplianceTester#196]
Conversations report that kode.im has XEP-0313 support, while ComplianceTester reports fail.

**Comment by licaon-kter** [comment]
For MUCs or 1:1?

**Comment by iNPUTmice** [comment]
Is this for MAM or MUC MAM?

**Comment by luweitest** [comment]
The last item：
 XEP-0313: Message Archive Management (MUC)…            FAILED
cmd line is
java -jar ComplianceTester-0.2.3.jar <user> <password>

**Comment by iNPUTmice** [comment]
I’m fairly certain the test is correct and that server doesn’t support MUC MAM.
