### ISSUE TITLE
Mention "--add-modules java.xml.bind" in README?

### ISSUE THREAD

**Issue by MarcelWaldvogel** [iNPUTmice/ComplianceTester#198]
I would suggest you mention that this option should be added on newer Java versions.

**Comment by licaon-kter** [comment]
How new?

**Comment by MarcelWaldvogel** [comment]
The workaround option has been mentioned as far back as #143. The goal of this issue is to give testers a direct hint while the problem is being solved.

I.e. "If the command fails with `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`. add `--add-modules java.xml.bind` to the command line."
