### ISSUE TITLE
Monochromacy friendly mode?

### ISSUE THREAD

**Issue by Mikaela** [iNPUTmice/ComplianceTester#202]
I am using my Android in monochromatic mode which can be enabled in developer settings under Hardware accelerated rendering, simulate colour space.

The greens and red can be distinguished until some server is selected which turns everything same colour.

I think this may also prevent colour blind people from using the online version.

**Comment by RishiRaj22** [comment]
Added in [cf7c7a545a27cfc0d54c25394fac1933a191f9c2](https://github.com/iNPUTmice/caas/commit/cf7c7a545a27cfc0d54c25394fac1933a191f9c2).
BTW the new repository for this project is at [iNPUTmice/caas](https://github.com/iNPUTmice/caas)
