### ISSUE TITLE
digital ocean droplet or AWS AMI

### ISSUE THREAD

**Issue by brighterness** [iNPUTmice/ComplianceTester#203]
Or an easy way for a non programmer to deploy an instance?  Perhaps in Amazon AWS free tier?

I am hoping an instance would be easier to test potential services for friends than registering a JID, then using Pix-Art Messenger or Conversations to view server features.

**Comment by iNPUTmice** [comment]
You can use [compliance.conversations.im](https://compliance.conversations.im).

**Comment by brighterness** [comment]
oh, that is sooooper awesome.  Thank you!
