### ISSUE TITLE
Add a way to make donations

### ISSUE THREAD

**Issue by tuxayo** [iNPUTmice/ComplianceTester#26]
Whether it's a cryptocurrency, [Bountysource](https://www.bountysource.com/), [BitHub](https://whispersystems.org/blog/bithub/), wire transfer or even Paypal.

People should be able to pay a drink to the maintainer because this project is awesome :-D

**Comment by iNPUTmice** [comment]
To be honest this particular project feels to insignificant to me to explicitly ask for donations. However if you like me work in general I have donation information for my main project the Conversations XMPP client. https://conversations.im/#donate

**Comment by tuxayo** [comment]
Great I didn't knew you work on Conversations! It's precisely for Conversations that I've used this project. I'm planning to stick with the default server and pay for it after the sixth month, good to know that will contribute to pay your bills.
