### ISSUE TITLE
Please add dreamhost

### ISSUE THREAD

**Issue by gwasher** [iNPUTmice/ComplianceTester#47]
DreamHost, a webhosting company, includes xmpp server for all domains in a VPS account such that one's email address may double as xmpp jid :) -- and sip uri with OpenVBX.  Sadly OpenVBX does not [yet] offer sip simple (texting).

> mail.dreamhost.com

is what VPS support says to use as host address for client.  It does not use SRV.

https://help.dreamhost.com/hc/en-us/articles/216674928-Jabber-overview

**Comment by iNPUTmice** [comment]
I can't add this without an account. But you can test it yourself and create a pull request for the report.

Or you can (temporarily) create an account for me.
