### ISSUE TITLE
XEP-0198: Stream Management test fails

### ISSUE THREAD

**Issue by capstab** [iNPUTmice/ComplianceTester#54]
I have a Prosody Server (hg:cdffbda59b03). When I run the test it fails:

running XEP-0115: Entity Capabilities…		FAILED
running XEP-0198: Stream Management…		FAILED

What I get is XEP-0115 because Prosody doesn't support it so far.  
The Problem I have with XEP-0198. In my Prosody I activated the smacks modules:

> smacks
> smacks_noerror
> smacks_oflfine

In the Prosody Consol I reloaded all modules:

> module:reload("smacks")
> | Reloaded on ****.*****.***
> | OK: Module reloaded on 1 host

> module:reload("smacks_noerror")
> | Reloaded on ****.*****.***
> | OK: Module reloaded on 1 host

> module:reload("smacks_offline")
> | Reloaded on ****.*****.***
> | OK: Module reloaded on 1 host

Im not sure if the ComplianceTester makes some mistake or if something is wrong with my Prosody.
Im out of Ideas. Hope someone can give me a hint.

**Comment by iNPUTmice** [comment]
This seems to be an error on your prodody. I think you have to update the modules.
