### ISSUE TITLE
Also test for XEP-0156

### ISSUE THREAD

**Issue by linkmauve** [iNPUTmice/ComplianceTester#76]
This XEP is very useful for web clients, which can’t use the traditional TCP-based connexion, nor do any DNS request, or when XEP-0368 isn’t supported yet and the client is behind a restrictive firewall.

When the user wants to use a web client hosted anywhere, having XEP-0156 supported on the service means that they can query either a TXT record from the DNS, or parse a simple XML file to know about the BOSH or WebSocket endpoint.

**Comment by Echolon** [comment]
Is that really necessary for a general good user experience? I think that's what the tester is about, or?

**Comment by linkmauve** [comment]
This is mandatory if you want to use any web client, without having to ask the user to input an awkward URL that is often hard to find. Most people will only use a desktop or mobile client, but some will prefer a web client, or will have no choice at all (e.g. on computers where they can’t install programs), this XEP makes it painless.

**Comment by iNPUTmice** [comment]
The caas can do it.
