### ISSUE TITLE
Server software

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/ComplianceTester#98]
Any chance of adding a last column that states (if known) the server software used?

This can be helpful for users (eg. testing out a bug that might be in one server type but not another) and other server admins (eg. popular server software).

Thanks

**Comment by participante0** [comment]
Anyone can visit xmpp.net in order to get that and many other info (now is temorary down).

**Comment by licaon-kter** [comment]
Luckily for me, I was searching this info when their system&backup was gone bye-bye. :-|

**Comment by iNPUTmice** [comment]
The detailed reports here in this repository do have these kind of information.
